services:
  apikwalifikacyjne:
    image: apikwalifikacyjne
    network_mode: bridge
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: ApiKwalifikacyjne/Dockerfile
